### ISSUE TITLE
while true

### ISSUE THREAD

**Issue by malhal** [Whiffer/swiftdata-sectionedquery#1]
More of a question than an issue sorry!

Regarding the `while true` at: https://github.com/Whiffer/swiftdata-sectionedquery/blob/dd5f481e8fc1a7977511e6e569af957d5e92ee67/Sources/SectionedQuery/SectionedQuery.swift#L75

And corresponding Task<Never, Never> at: https://github.com/Whiffer/swiftdata-sectionedquery/blob/dd5f481e8fc1a7977511e6e569af957d5e92ee67/Sources/SectionedQuery/SectionedQuery.swift#L20

I was wondering why you went for `Task<Never, Never>` and `while true` instead of just `Task<Void, Never>` with no while loop? Given the for await already loops forever. Cheers

**Comment by Whiffer** [comment]
Good observation.  That was one of the last pieces I coded and I stopped working on it as soon as I got it working.  I will eliminate the unnecessary code.  Thanks.

**Comment by Whiffer** [comment]
I made the change. Thanks again for the observation.

**Comment by rlaurb** [comment]
This is just a comment you might find amusing (not an issue by any means, but I couldn't figure out a better way to contact you).

I wanted to use `@SegmentedQuery`, but needed a way to present the sections in a special order (which could not be easily described by a `SortDescriptor`. So I modified it, **but** needed a way to communicate between the `View` that declares the `@SectionedQuery` and the property wrapper itself. This turned out to be a Delegate pattern. 

The whole thing works great and I thought you'd find the code amusing. A writeup it attached. 

Thank you for writing swiftdata-sectionedquery -- it is tremendously helpful in my application. 
[Extending-the-Delegate-Pattern-to-SwiftUI.pdf](https://www.dropbox.com/scl/fi/4sdwk7vvxy3aaa8dhtb2t/Extending-the-Delegate-Pattern-to-SwiftUI.pdf?rlkey=q6a7na5yh1ox90vcfm6saf2i3&dl=0)

**Comment by malhal** [comment]
Unfortunately since View structs are values they have no lifetime so they can't be a delegate. You could be benefiting from some kind of side effect of forcing body to be called by changing the value of the query every time the View is init.

I don't know what way you want to communicate but one option is to access something inside the query as a binding, the same as how nsPredicate on @FetchRequest works. The major flaw in that approach is if the View is re-init then any changes are lost but it can be worked around by setting it in a computed property before accessing the wrappedValue.

**Comment by rlaurb** [comment]
I’m a newbie to SwiftUI (but an old — in both time and age — hand at UIKit and CoreData). It seems to me that the basic View struct (i.e., the ContentView or whatever) has a lifetime for as long as the view it represents is on-screen; it is the body of the View which it transient. So the delegate is alive for exactly how long I want it to be. In a NavigationStack, it appears that the View lives as long as it is in the stack, even if another view is pushed (or presented as a sheet) on top of it. (And, I think, that some of @Query’s update problems are related to this.) 

So (in my hopefully humble newbie way) I must disagree that the delegate cannot be used on a struct. I think it can, as long as one keeps the actual lifetime of the struct in mind.

One value of using the delegate pattern is that its use is optional. So (given proper coding of the feature extensions), I can (and do) use the delegate where it is needed and not use it where it is not. Being able to conditionalize the special feature implementation based on whether var delegate: Delegate?  is nil or not is quite useful.

Cheers,

Rick Aurbach

“Learning from experience is a faculty almost never practiced.”
– Barbara Tuchman, historian (1912–1989)

**Comment by Whiffer** [comment]
Rick, on the surface, it seems like you are creating an overly complex solution for your situation.  If you can solve your problem with a very complex solution (i.e. hack),  more elegant solutions most certainly do exist if you dig deeper.  I've thought about it a lot and I'm not sure I see how the delegate pattern (e.g. callbacks) can ever be an elegant solution.  Avenues that I would pursue would be to use a custom SortComparator, the property wrapper's Configuration structure, the Environment, or a StateObject.  Good luck.

Thanks,
Chuck

**Comment by rlaurb** [comment]
Chuck,

Thank you very much for your input. I don’t disagree with you. I will think more about the best approach, although I’ll probably stick with my (admittedly overly-complex) solution.

I’m basically solving two problems:
(1) a case where the section sort order is user-defined and managed externally to the place where @SectionedQuery is used. (I understand how this problem could be solved by a database schema change, but that change introduces other problems in the application, so I’m loathe to do it.)
(2) a case where I need to include sections which are empty, based on a user-defined, user-extensible list of cases. That is, the user defines a set of sections (based on a starter list that is built-in). In this particular sectioned list, I need to show all of them (whether or not they contain any objects. The list of possible sections is available externally to the place where @SectionedQuery is used, and must be formed dynamically (since the user can add or remove section categories).

I realize that these are weird cases, but they work for my app.

I’m thinking that I could probably avoid solve these problems by introducing an extensible Configuration. I would also have to move some of the fetchSectionedResults logic into a module that can be replaced when @SectionedQuery is inited. Not sure that’s any less complex than what I’m doing now, though.  Hmm. More thought is clearly needed.

Anyway, you’ve given me a lot to think about and I appreciate it.
 
Cheers,

Rick Aurbach

“Patriotism is supporting your country all the time and your government when it deserves it”
— Mark Twain

**Comment by malhal** [comment]
> It seems to me that the basic View struct (i.e., the ContentView or whatever) has a lifetime for as long as the view it represents is on-screen; it is the body of the View which it transient. 

Haha yes `ContentView` does lull you into that false sense of security but I assure you while things are on screen (mostly UIKit UIView objects by the way) the `View` structs are being init over and over again, fortunately that is as lightweight as creating an Int. The `View` struct's body is being diffed from last time it was init and the difference is used to create/update/remove UIKit objects. Because `ContentView` is the top level it can seem to be just init once but all of the `View` structs below it are init constantly and `body` is only called if the params passed into the View init are different from last time. However since it can only compare properties that are value types so if you pass in a closure or define certain property wrappers, e.g. `@AppStorage`, then it can't do a comparison so `body` is always called. Fortunately, you can structure your View hierarchy (tip make small ones!) so the `body`s that are always called are small ones and pass the data from the property wrapper down so the data can be diffed in the child View and perhaps `body` might not be called if the data hadn't changed.

I recommend testing your solution by simulating your View struct containing your property wrapper being re-init, a simple way is with a button, e.g.
```
struct ContentView {
    @State var counter = 0
    var body: some View {
        VStack {
            Button("Inc \(counter)") {
                counter += 1
           }
            YourViewWithSectionedRequest() // its body shouldn't be called the second time but can be if certain property wrappers are used.
        }
    }
}
```

**Comment by Whiffer** [comment]
To your point (1), you're correct, making a schema change definitely seems like the right thing to do.  Sometimes it's not worth beating your head against the wall to avoid doing something you are trying to avoid.  I have completely rewritten large sections of some of my Apps several times and in the end, I was always been happy that I did.

As @malhal points out, there is a lot going on under the hood. Try adding this in the body of your ContentView (or the body of any other View):
`        let _ = Self._printChanges()
`
I would also recommend that you (re)watch Demystify SwiftUI from WWDC21.
